import "./globals.css";
import CommonLayout from "@/components/common-layout";
import { SidebarProvider } from "@/components/ui/sidebar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        
        <CommonLayout children={children}/>
        
      </body>
    </html>
  );
}
