import { Suspense } from 'react';
import Loading from './loading';
import './globals.css';
import CommonLayout from '@/components/common-layout';
import { ClerkProvider } from '@clerk/nextjs';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return( 
  <ClerkProvider>
    
    <html lang="en">
      <body
        className=""
      >
        <Suspense fallback={<Loading/>}>
            <CommonLayout children={children}/>

        </Suspense>
      </body>
    </html>
  
  </ClerkProvider>
  )
}
